title: Harte
url: ""
baseurl: "/blog"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Last Update: 2023.8.4.   All Rights Reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "主页"
   link: "/blog/"
 - name: "简历"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
