title: 杨强
url: "harte.top"
baseurl: "https://harteyang.github.io/index/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "Last Update: 2023.8.4.   All Rights Reserved."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "主页"
   link: "https://harteyang.github.io/index/"
 - name: "简历"
   link: "resume.pdf"
 - name: "博客"
   link: "https://harteyang.github.io/post/"
