title: 不惑偶书
url: "https://harte.top"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: ""
footer_text: "更新于2025年3月，作者保留所有权利。"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "简历"
   link: "https://harteyang.github.io/resume/"
#  link: "https://harte.top/杨强-人力资源管理10年以上.pdf"
 - name: "博客"
   link: "https://blog.harte.top"
